#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : spdlog
Version  : 1.4.2
Release  : 2
URL      : https://github.com/gabime/spdlog/archive/v1.4.2.tar.gz
Source0  : https://github.com/gabime/spdlog/archive/v1.4.2.tar.gz
Summary  : Fast C++ logging library.
Group    : Development/Tools
License  : MIT
Requires: spdlog-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : glibc-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(fmt)
BuildRequires : pkgconfig(libsystemd)

%description
# spdlog
Very fast, header-only/compiled, C++ logging library. [![Build Status](https://travis-ci.org/gabime/spdlog.svg?branch=master)](https://travis-ci.org/gabime/spdlog)&nbsp; [![Build status](https://ci.appveyor.com/api/projects/status/d2jnxclg20vd0o50?svg=true)](https://ci.appveyor.com/project/gabime/spdlog)

%package dev
Summary: dev components for the spdlog package.
Group: Development
Requires: spdlog-lib = %{version}-%{release}
Provides: spdlog-devel = %{version}-%{release}
Requires: spdlog = %{version}-%{release}

%description dev
dev components for the spdlog package.


%package lib
Summary: lib components for the spdlog package.
Group: Libraries

%description lib
lib components for the spdlog package.


%prep
%setup -q -n spdlog-1.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571170004
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DSPDLOG_BUILD_BENCH=OFF \
-DSPDLOG_BUILD_EXAMPLES=OFF \
-DSPDLOG_FMT_EXTERNAL=ON \
-DSPDLOG_BUILD_SHARED=ON \
-DCMAKE_BUILD_TYPE=Release
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1571170004
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/spdlog/cmake/spdlogConfig.cmake
/usr/lib64/spdlog/cmake/spdlogConfigTargets-release.cmake
/usr/lib64/spdlog/cmake/spdlogConfigTargets.cmake
/usr/lib64/spdlog/cmake/spdlogConfigVersion.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/spdlog/async.h
/usr/include/spdlog/async_logger-inl.h
/usr/include/spdlog/async_logger.h
/usr/include/spdlog/common-inl.h
/usr/include/spdlog/common.h
/usr/include/spdlog/details/backtracer-inl.h
/usr/include/spdlog/details/backtracer.h
/usr/include/spdlog/details/circular_q.h
/usr/include/spdlog/details/console_globals.h
/usr/include/spdlog/details/file_helper-inl.h
/usr/include/spdlog/details/file_helper.h
/usr/include/spdlog/details/fmt_helper.h
/usr/include/spdlog/details/log_msg-inl.h
/usr/include/spdlog/details/log_msg.h
/usr/include/spdlog/details/log_msg_buffer-inl.h
/usr/include/spdlog/details/log_msg_buffer.h
/usr/include/spdlog/details/mpmc_blocking_q.h
/usr/include/spdlog/details/null_mutex.h
/usr/include/spdlog/details/os-inl.h
/usr/include/spdlog/details/os.h
/usr/include/spdlog/details/pattern_formatter-inl.h
/usr/include/spdlog/details/pattern_formatter.h
/usr/include/spdlog/details/periodic_worker-inl.h
/usr/include/spdlog/details/periodic_worker.h
/usr/include/spdlog/details/registry-inl.h
/usr/include/spdlog/details/registry.h
/usr/include/spdlog/details/synchronous_factory.h
/usr/include/spdlog/details/thread_pool-inl.h
/usr/include/spdlog/details/thread_pool.h
/usr/include/spdlog/fmt/bin_to_hex.h
/usr/include/spdlog/fmt/fmt.h
/usr/include/spdlog/fmt/ostr.h
/usr/include/spdlog/formatter.h
/usr/include/spdlog/logger-inl.h
/usr/include/spdlog/logger.h
/usr/include/spdlog/sinks/android_sink.h
/usr/include/spdlog/sinks/ansicolor_sink-inl.h
/usr/include/spdlog/sinks/ansicolor_sink.h
/usr/include/spdlog/sinks/base_sink-inl.h
/usr/include/spdlog/sinks/base_sink.h
/usr/include/spdlog/sinks/basic_file_sink-inl.h
/usr/include/spdlog/sinks/basic_file_sink.h
/usr/include/spdlog/sinks/daily_file_sink.h
/usr/include/spdlog/sinks/dist_sink.h
/usr/include/spdlog/sinks/dup_filter_sink.h
/usr/include/spdlog/sinks/msvc_sink.h
/usr/include/spdlog/sinks/null_sink.h
/usr/include/spdlog/sinks/ostream_sink.h
/usr/include/spdlog/sinks/rotating_file_sink-inl.h
/usr/include/spdlog/sinks/rotating_file_sink.h
/usr/include/spdlog/sinks/sink-inl.h
/usr/include/spdlog/sinks/sink.h
/usr/include/spdlog/sinks/stdout_color_sinks-inl.h
/usr/include/spdlog/sinks/stdout_color_sinks.h
/usr/include/spdlog/sinks/stdout_sinks-inl.h
/usr/include/spdlog/sinks/stdout_sinks.h
/usr/include/spdlog/sinks/syslog_sink.h
/usr/include/spdlog/sinks/systemd_sink.h
/usr/include/spdlog/sinks/wincolor_sink-inl.h
/usr/include/spdlog/sinks/wincolor_sink.h
/usr/include/spdlog/spdlog-inl.h
/usr/include/spdlog/spdlog.h
/usr/include/spdlog/tweakme.h
/usr/include/spdlog/version.h
/usr/lib64/libspdlog.so
/usr/lib64/pkgconfig/spdlog.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspdlog.so.1
/usr/lib64/libspdlog.so.1.4.2
